language: cpp
dist: xenial
compiler:
    - clang
    - gcc
env:
    - LIBRARY_COMBO=gnu-gnu-gnu
    - LIBRARY_COMBO=ng-gnu-gnu
    - LIBRARY_COMBO=ng-gnu-gnu BASE_ABI=--disable-mixedabi
    - LIBRARY_COMBO=ng-gnu-gnu RUNTIME_VERSION=gnustep-2.0
    - LIBRARY_COMBO=ng-gnu-gnu BASE_ABI=--disable-mixedabi RUNTIME_VERSION=gnustep-2.0
matrix:
    exclude:
        - compiler: gcc
          env: LIBRARY_COMBO=ng-gnu-gnu
        - compiler: gcc
          env: LIBRARY_COMBO=ng-gnu-gnu BASE_ABI=--disable-mixedabi
        - compiler: gcc
          env: LIBRARY_COMBO=ng-gnu-gnu RUNTIME_VERSION=gnustep-2.0
        - compiler: gcc
          env: LIBRARY_COMBO=ng-gnu-gnu BASE_ABI=--disable-mixedabi RUNTIME_VERSION=gnustep-2.0
        - compiler: clang
          env: LIBRARY_COMBO=gnu-gnu-gnu
sudo: required
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y cmake pkg-config libgnutls28-dev libgmp-dev libffi-dev libicu-dev libxml2-dev libxslt1-dev libssl-dev libavahi-client-dev zlib1g-dev
    - >
        if [ $LIBRARY_COMBO = 'gnu-gnu-gnu' ];
        then
          if [ $CC = 'gcc' ];
          then
            sudo apt-get install -y gobjc;
          fi;
          sudo apt-get install -y libobjc-4.8-dev libblocksruntime-dev;
        else
          sudo apt-get install -y libkqueue-dev libpthread-workqueue-dev;
        fi;
    # libdispatch requires a fairly recent version of cmake
    - >
        if [ $LIBRARY_COMBO = 'ng-gnu-gnu' ];
        then
          curl -LO https://cmake.org/files/v3.15/cmake-3.15.5-Linux-x86_64.tar.gz;
          tar xf cmake-3.15.5-Linux-x86_64.tar.gz;
          mv cmake-3.15.5-Linux-x86_64 $HOME/cmake;
          export PATH=$HOME/cmake/:$HOME/cmake/bin:$PATH
        fi;
install: ./travis-deps.sh
before_script: >
    export LIBRARY_PATH=$HOME/staging/lib:$HOME/staging/lib64:$LIBRARY_PATH;
    export LD_LIBRARY_PATH=$HOME/staging/lib:$HOME/staging/lib64:$LD_LIBRARY_PATH;
    if [ $LIBRARY_COMBO = 'ng-gnu-gnu' ];
    then
      export CPATH=$HOME/staging/include;
    else
      export CPATH=/usr/lib/gcc/x86_64-linux-gnu/4.8/include;
    fi;
    export PATH=$HOME/staging/bin:$PATH;
    export GNUSTEP_MAKEFILES=$HOME/staging/share/GNUstep/Makefiles;
    . $HOME/staging/share/GNUstep/Makefiles/GNUstep.sh;
script: >
    ./configure $BASE_ABI;
    make && make install && make check || (cat Tests/tests.log && false);
